# Generated by Django 4.0.2 on 2025-11-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_model',
            new_name='Player',
        ),
    ]
